# Generated by Django 5.0.1 on 2024-02-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('small_description', models.CharField(max_length=50)),
                ('sellig_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.IntegerField()),
                ('description', models.TextField()),
                ('brand_image', models.ImageField(upload_to='watch_images')),
            ],
        ),
    ]
