# Generated by Django 5.0.1 on 2024-02-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='sellig_price',
            new_name='selling_price',
        ),
    ]
