# Generated by Django 5.0.1 on 2024-03-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0003_alter_watch_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='categories',
            field=models.CharField(choices=[('Home', 'Home'), ('product', 'product'), ('strap', 'strap')], default='NA', max_length=100),
        ),
    ]
