# Generated by Django 5.0.1 on 2024-03-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0006_alter_watch_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='brand_image',
            field=models.ImageField(upload_to='media/watch_images'),
        ),
    ]
