# Generated by Django 5.0.1 on 2024-03-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0009_watch_price_and_quantity_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='price_and_quantity_total',
            field=models.IntegerField(default=1999),
        ),
    ]
